# Generated by Django 4.2.1 on 2023-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(choices=[('New Installation', 'New Installation'), ('Support', 'Support'), ('Re-Connection', 'Re-Connection')], default='Support', max_length=50),
        ),
    ]
