# Generated by Django 4.2.1 on 2023-06-05 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0003_alter_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
